battlefield_bangkok:
  api_host: https://battlefield-bangkok.myshopify.com
  store_name: btf_bkk
boarding_time:
  api_host: https://boardingtimegames.com
  store_name: bdt
sources:
  raw_dir: public/sources/
  formatted_dir: public/sources/formatted/
thai_bulk:
  api_url: https://secure.thaibulksms.com/sms_api_test.php
  username: thaibulksms
  password: thisispassword
